### ISSUE TITLE
Asking help about the Collector Module Installation?

### ISSUE THREAD

**Issue by darapenhchet** [ria-ee/X-Road-opmonitor#5]
Dear XRoad,

Could I ask you about this problem?

![image](https://user-images.githubusercontent.com/8038324/68929418-ee373e80-07be-11ea-8d43-0d89c0f6aa51.png)

Best Regards,
Dara Penhchet

**Comment by ToomasMolder** [comment]
This Warning means, that no getSecurityServerOperationalData pacakages received form all the listed 4 security servers. To understand the actual reason, the one option is to increase temporarily logging level LOGGER_LEVEL available at settings.py.

The reasons migt be:
- security server version in client side is low/old (below 6.9.5) so, that operational monitoring is not supported yet;
- security servers installed in client side do not have operational monitoring package installed, activated at all;
- security servers  installed in client side do not have firewall ports TCP/5500 and 5577 open for central server, they do not allow requests;
- there is no actual X-Road traffic data available (yet) in listed client security servers
- etc etc

**Comment by darapenhchet** [comment]
Dear @ToomasMolder ,

- I have installed the Security Server version 6.22
- Security Server I have not yet installed the Operational Monitoring packaged.
- I have allowed the TCP/5500 and 5577 already
- I have tried to request some data already.

So I will try to install the XRoad Operational Monitoring package

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @ToomasMolder ,

I have installed the XRoad Operation Monitoring already, but it still not work.

Do you have any solution more?

Best Regards,
Dara Penhchet

**Comment by darapenhchet** [comment]
Dear @ToomasMolder ,

I have tried to install that XRoad Operation Monitoring. and Execute this command
`sudo --user collector ./collector_module/cron_collector.sh update`


2019-11-18 10:24:04,663 [qtp1204178174-52] INFO  e.r.x.p.s.ServerMessageProcessor - process(multipart/mixed; charset=UTF-8; boundary=xtopCIhhGfcdVYXVcsEMRiFUiOwvdTgowz)
2019-11-18 10:24:04,702 [qtp1204178174-52] ERROR e.r.x.p.s.ServerProxyHandler - Request processing error (1fc577eb-903a-409d-afec-e9c18ed3ee1b)
ee.ria.xroad.common.CodedException: Server.ServerProxy.UnknownService: Unknown service: SERVICE:CAM/GOV/1234/getSecurityServerOperationalData

Best Regard,
Dara Penhchet

**Comment by ToomasMolder** [comment]
Dear @darapenhchet ,

Sorry for delay in answering, I'm out of office until Nov 25th.
There seems to be some issue with xRoadInstance CAM Central Server or Central Monitoring Server or client(s) security server(s) installation. All these possibilities are pretty hard to debug as I do not have overview of your installation settings and am not the X-Road core system expert.

Are you administrator of CAM Central Server or Central Monitoring Server or trying to set up the system from Member's Security Server perspective? 

Please clarify about CAM (or CAMBODIA?) global configuration anchor available. It is usually public as design of X-Road (for example, Estonian anchors are https://x-tee.ee/anchors/). Do you run xRoadInstance 'CAM' or 'CAMBODIA' (the error messages you forwarded had different logs so far). Please notice, that is is NOT possible to monitor X-Road of some instance from another instance.

From anchor I might see, what is configured to be Central Server, what is configured to be as Central Monitoring Server (it has access to all Members Security Servers by design) and what are the Members Security Servers.
I've understood so far, that the list of members Security Servers is:
CAMBODIA/GOV/1234/178.128.122.111
CAMBODIA/GOV/201901/157.230.36.180
CAMBODIA/GOV/201902/206.189.145.147
CAMBODIA/GOV/201903/178.128.22.140
Am I right?

Please note, that both Central Monitoring Server and all Members Security Servers must have operational monitoring package (xroad-opmonitor) available and running. It might be, that one or some or all of them missing. To see the packages running, please execute command 'dpkg -l | egrep "xroad|xtee" | sort' from the command prompt of each of the security servers.

What server is configured as Central Monitoring Server?
Please review the file settings.py from your system directory (probably) /srv/app/CAM/collector-module/settings.py

If it is possible, I ask also to continue this debugging through email, toomas.molder@ria.ee as it seems to me, that the issue it is not about Operational Monitoring solution or Collector Module, it is about xRoadInstance CAM (or CAMBODIA) configuration. Will try to consult also with my colleges, Estonian X-tee service managers.

**Comment by ToomasMolder** [comment]
Please ensure, that 'apt install xroad-addon-opmonitoring' is installed in both Central Monitoring Server and Members Security Servers.

**Comment by darapenhchet** [comment]
Dear @ToomasMolder ,
What is the Central Monitoring Server? How could we install and configure it?

Best Regards,
Dara Penhchet
